<a href="https://colab.research.google.com/github/Klark-cyber/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.2

In [37]:
# DataFrame bu berilgan dictionaryni table korinishidagi holatga otkazib beradi
mydataset = {
  'cars': ["BMW", "Volvo", "Ford","BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2, 4, 6, 9]
}

df = pd.DataFrame(mydataset)

print(df)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
3    BMW         4
4  Volvo         6
5   Ford         9

In [35]:
print(df)

  cars  passings
0  BMW         3
1  BMW         7
2  BMW         2
3  BMW         4
4  BMW         6
5  BMW         9

In [10]:
# df.head() bu method tabledagi kerakli qatorgach bolgan qismni qaytaradi.default 5 ta. 0 bolsa faqat ustun nomlarini qaytaradi. -1 qiymat bersak eng oxirgidan tashqari qolgan datani qaytaradi
df.head()

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
3    BMW         4
4  Volvo         6

In [11]:
#df.tail() bu df.headning qaramaqarshi methodi yani oxiridan yuqoriga qarab yuradi. -1 1 elementdan tashqari barcha tableni qaytaradi.0 faqat column nameni, 1 eng oxirgi elementni
df.tail()

    cars  passings
1  Volvo         7
2   Ford         2
3    BMW         4
4  Volvo         6
5   Ford         9

In [12]:
#df.shape bu qator va ustun sonlarini aniqlab beradi. bu method emas property
df.shape

(6, 2)

In [13]:
# columns bu berilgan dataning taypi va column namelarini qaytaradi
df.columns

Index(['cars', 'passings'], dtype='object')

In [14]:
# types bu berilgan dataning typini korsatadi faqat boshqacha korinishda
df.dtypes

cars        object
passings     int64
dtype: object

In [16]:
# describe bu berilgan dataning faqat raqamdan iborat ustunini tanlab u haqida statistic malumotlarni beradi
df.describe() # default faqat numberlarni tanlaydi lekin (include="all") qilsak barcha ustunlarni ham tanlab beradi

       passings
count  6.000000
mean   5.166667
std    2.639444
min    2.000000
25%    3.250000
50%    5.000000
75%    6.750000
max    9.000000

In [19]:
# iloc bu berilgan qiymatga teng qatordagi malumotni qaytaradi. [x:], [x,y], [x] korinishdagi qiymatlarni kiritishimiz mumkin
df.iloc[0]

cars        BMW
passings      3
Name: 0, dtype: object

In [25]:
# loc bu 2 ta argument olib 1-kerakli qatordagi qiymat 2-column nameni qabul qiladi
df.loc[0:, "cars"]

0      BMW
1    Volvo
2     Ford
3      BMW
4    Volvo
5     Ford
Name: cars, dtype: object

In [45]:
# bu ifoda matritsa ustida amal bajarish imkonini beradi "df["passings"] > 3" bu faqat boolean qaytaradi ammo uni df[df["passings"] > 3] qilsak bizga natija qaytaradi
df[df["passings"] == 7]

    cars  passings
1  Volvo         7

In [55]:
# mean bu berilgan labeldagi sonlar yigindisini ortachasini chiqaradi
df.mean(numeric_only=True) # yoki
df['passings'].mean()

np.float64(5.166666666666667)

In [56]:
# sum() barcha ustundagi elementlarni ozaro qoshib chop etadi
df.sum()

cars        BMWVolvoFordBMWVolvoFord
passings                          31
dtype: object

In [57]:
df.min()

cars        BMW
passings      2
dtype: object

In [58]:
df.max()

cars        Volvo
passings        9
dtype: object

In [61]:
# median ortacha qiymatni float korinishda olib beradi
df.median(numeric_only=True)

passings    5.0
dtype: float64

In [62]:
df.count() # count bu null valuelarni olib tashlab qolganini qaytaradi

cars        6
passings    6
dtype: int64

In [63]:
df.std(numeric_only=True) #standart deveation yani ortacha qiymatdan qancha birlik uzoqda ekanligini aniqlaydi

passings    2.639444
dtype: float64

In [67]:
missing_data = {
  'cars': ["BMW", None , "Ford","BMW", None, "Ford"],
  'passings': [3, None, 2, None, 6, 9]
}

md = pd.DataFrame(missing_data)

print(md)

   cars  passings
0   BMW       3.0
1  None       NaN
2  Ford       2.0
3   BMW       NaN
4  None       6.0
5  Ford       9.0

In [69]:
md.isnull() # boolena qaytaradi.bor datalarga false, null datalarga true qiymat beradi.
md.isnull().sum() #labelga tegishli elementlar orasida null qiymatdagi elementlarning umumiy sonini qaytaradi

cars        2
passings    2
dtype: int64

In [75]:
md.dropna() #default qaysi qatorda xech bolmasa 1 dona null,NaN, None bor bolsa osha qatorni tashlab yuboradi qaysi labelda bolishidan qatiy nazar.
md.dropna(how="all") # faqat qator boylab barcha elementi falsy bolgan qatornigina ochiradi.
md.dropna(axis=1) #bunda qaysi labelda bir dona bolsa ham falsy bolsa osha labelni ochirib yuboradi.
md.dropna(subset=['passings']) #faqat kerakli labeldagi fulsy datalarni olib tashlaydi.qolgan columnlarni etiborsiz qoldiradi

   cars  passings
0   BMW       3.0
2  Ford       2.0
4  None       6.0
5  Ford       9.0

In [78]:
md.fillna(0) # tabledagi barcha fulsy kataklarga 0 yoki argument sifatidag kiritilgan textni qoyadi.
md.fillna({"cars": "unknown", "passings": 0}) #cars unknown matni , passingsga 0 qiymat kiritadi

      cars  passings
0      BMW       3.0
1  unknown       0.0
2     Ford       2.0
3      BMW       0.0
4  unknown       6.0
5     Ford       9.0

In [80]:
df=pd.read_csv("Titanic-Dataset.csv") # titanic datasetni pandas orqali oqiymiz.
df.head() # kerakli qator qiymatini kiritib 0 dan osha qatorgcha bolgan tableni quramizs
# df=pd.read_excel("Titanic-Dataset.xlsx") excel file format uchun
# df=pd.read_json("Titanic-Dataset.json") json file format uchun

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [83]:
df.to_excel("test.xlsx") #yuqoridagi dataga ishlov bergach endi uni excel formatga otkazib saqlab qoyamiz. kerakli file formati to_json... kabi tanlab olinaveradi

In [91]:
# Series bu asosan 1D olchamli arraylar ustida ishlashda foydalaniladi
cars = pd.Series(["BMW", "Tesla", "Ferrari"]) #bu yerda series arrayni jadval korinishida chiqarib berdi
#print(cars)
carss = mydataset["cars"]
print(carss)

['BMW', 'Volvo', 'Ford', 'BMW', 'Volvo', 'Ford']